### ISSUE TITLE
Add support for different level Enchanting (/enchant <tier>).

### ISSUE THREAD

**Issue by ItsSchatten** [ItsSchatten/PortableCraftingInvs#2]
You want to suggest something for the plugin? Go ahead, if you are a developer yourself you can even clone this repository and make a pull request for your suggestion!

**What is your suggestion?**
*What is the suggestion you are proposing?*

Try and add support for different tier enchanting.

**How should this suggestion work?**
*How should I attempt to make this suggestion work?*

This feature should add support for different levels of enchanting like level 30 enchantment levels with only a "regular" enchantment inventory. This enchantment table still requires users to have lapis and levels for their enchantments.
Add support to different levels of enchanting? Add support to enable or disable this function.

**Comment by ItsShadow13** [comment]
While not necessarily implemented in a command type way, due to way that the Spigot-API opens an Enchantment table, it acts like a physical one.

What this means is that if you stand near any bookshelves the appropriate bonus will be applied, while not what I wanted it works for the time being until I can figure something else out.

**Comment by ItsSchatten** [comment]
Might be possible with NMS.
